// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/log_message.proto

package cn.learning;

public final class LogMessageOuterClass {
  private LogMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.learning.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string log_type = 1;</code>
     */
    java.lang.String getLogType();
    /**
     * <code>string log_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getLogTypeBytes();

    /**
     * <code>string collect_time_hour = 2;</code>
     */
    java.lang.String getCollectTimeHour();
    /**
     * <code>string collect_time_hour = 2;</code>
     */
    com.google.protobuf.ByteString
        getCollectTimeHourBytes();

    /**
     * <code>int32 net_dom = 3;</code>
     */
    int getNetDom();

    /**
     * <code>string collect_ip = 4;</code>
     */
    java.lang.String getCollectIp();
    /**
     * <code>string collect_ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getCollectIpBytes();

    /**
     * <code>string collect_time_date = 5;</code>
     */
    java.lang.String getCollectTimeDate();
    /**
     * <code>string collect_time_date = 5;</code>
     */
    com.google.protobuf.ByteString
        getCollectTimeDateBytes();

    /**
     * <code>int64 collect_time = 6;</code>
     */
    long getCollectTime();

    /**
     * <code>string dev_ip = 7;</code>
     */
    java.lang.String getDevIp();
    /**
     * <code>string dev_ip = 7;</code>
     */
    com.google.protobuf.ByteString
        getDevIpBytes();

    /**
     * <code>string raw_msg = 8;</code>
     */
    java.lang.String getRawMsg();
    /**
     * <code>string raw_msg = 8;</code>
     */
    com.google.protobuf.ByteString
        getRawMsgBytes();

    /**
     * <code>string dev_type = 9;</code>
     */
    java.lang.String getDevType();
    /**
     * <code>string dev_type = 9;</code>
     */
    com.google.protobuf.ByteString
        getDevTypeBytes();

    /**
     * <code>string serial_num = 10;</code>
     */
    java.lang.String getSerialNum();
    /**
     * <code>string serial_num = 10;</code>
     */
    com.google.protobuf.ByteString
        getSerialNumBytes();
  }
  /**
   * Protobuf type {@code cn.learning.LogMessage}
   */
  public  static final class LogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.learning.LogMessage)
      LogMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMessage() {
      logType_ = "";
      collectTimeHour_ = "";
      netDom_ = 0;
      collectIp_ = "";
      collectTimeDate_ = "";
      collectTime_ = 0L;
      devIp_ = "";
      rawMsg_ = "";
      devType_ = "";
      serialNum_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              logType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              collectTimeHour_ = s;
              break;
            }
            case 24: {

              netDom_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              collectIp_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              collectTimeDate_ = s;
              break;
            }
            case 48: {

              collectTime_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              devIp_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              rawMsg_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              devType_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              serialNum_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.learning.LogMessageOuterClass.internal_static_cn_learning_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.learning.LogMessageOuterClass.internal_static_cn_learning_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.learning.LogMessageOuterClass.LogMessage.class, cn.learning.LogMessageOuterClass.LogMessage.Builder.class);
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object logType_;
    /**
     * <code>string log_type = 1;</code>
     */
    public java.lang.String getLogType() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logType_ = s;
        return s;
      }
    }
    /**
     * <code>string log_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLogTypeBytes() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLLECT_TIME_HOUR_FIELD_NUMBER = 2;
    private volatile java.lang.Object collectTimeHour_;
    /**
     * <code>string collect_time_hour = 2;</code>
     */
    public java.lang.String getCollectTimeHour() {
      java.lang.Object ref = collectTimeHour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectTimeHour_ = s;
        return s;
      }
    }
    /**
     * <code>string collect_time_hour = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCollectTimeHourBytes() {
      java.lang.Object ref = collectTimeHour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectTimeHour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NET_DOM_FIELD_NUMBER = 3;
    private int netDom_;
    /**
     * <code>int32 net_dom = 3;</code>
     */
    public int getNetDom() {
      return netDom_;
    }

    public static final int COLLECT_IP_FIELD_NUMBER = 4;
    private volatile java.lang.Object collectIp_;
    /**
     * <code>string collect_ip = 4;</code>
     */
    public java.lang.String getCollectIp() {
      java.lang.Object ref = collectIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectIp_ = s;
        return s;
      }
    }
    /**
     * <code>string collect_ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCollectIpBytes() {
      java.lang.Object ref = collectIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLLECT_TIME_DATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object collectTimeDate_;
    /**
     * <code>string collect_time_date = 5;</code>
     */
    public java.lang.String getCollectTimeDate() {
      java.lang.Object ref = collectTimeDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectTimeDate_ = s;
        return s;
      }
    }
    /**
     * <code>string collect_time_date = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCollectTimeDateBytes() {
      java.lang.Object ref = collectTimeDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectTimeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLLECT_TIME_FIELD_NUMBER = 6;
    private long collectTime_;
    /**
     * <code>int64 collect_time = 6;</code>
     */
    public long getCollectTime() {
      return collectTime_;
    }

    public static final int DEV_IP_FIELD_NUMBER = 7;
    private volatile java.lang.Object devIp_;
    /**
     * <code>string dev_ip = 7;</code>
     */
    public java.lang.String getDevIp() {
      java.lang.Object ref = devIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devIp_ = s;
        return s;
      }
    }
    /**
     * <code>string dev_ip = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDevIpBytes() {
      java.lang.Object ref = devIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RAW_MSG_FIELD_NUMBER = 8;
    private volatile java.lang.Object rawMsg_;
    /**
     * <code>string raw_msg = 8;</code>
     */
    public java.lang.String getRawMsg() {
      java.lang.Object ref = rawMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string raw_msg = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRawMsgBytes() {
      java.lang.Object ref = rawMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rawMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEV_TYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object devType_;
    /**
     * <code>string dev_type = 9;</code>
     */
    public java.lang.String getDevType() {
      java.lang.Object ref = devType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devType_ = s;
        return s;
      }
    }
    /**
     * <code>string dev_type = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDevTypeBytes() {
      java.lang.Object ref = devType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERIAL_NUM_FIELD_NUMBER = 10;
    private volatile java.lang.Object serialNum_;
    /**
     * <code>string serial_num = 10;</code>
     */
    public java.lang.String getSerialNum() {
      java.lang.Object ref = serialNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serialNum_ = s;
        return s;
      }
    }
    /**
     * <code>string serial_num = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNumBytes() {
      java.lang.Object ref = serialNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLogTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logType_);
      }
      if (!getCollectTimeHourBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, collectTimeHour_);
      }
      if (netDom_ != 0) {
        output.writeInt32(3, netDom_);
      }
      if (!getCollectIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, collectIp_);
      }
      if (!getCollectTimeDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, collectTimeDate_);
      }
      if (collectTime_ != 0L) {
        output.writeInt64(6, collectTime_);
      }
      if (!getDevIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, devIp_);
      }
      if (!getRawMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, rawMsg_);
      }
      if (!getDevTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, devType_);
      }
      if (!getSerialNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, serialNum_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLogTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logType_);
      }
      if (!getCollectTimeHourBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, collectTimeHour_);
      }
      if (netDom_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, netDom_);
      }
      if (!getCollectIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, collectIp_);
      }
      if (!getCollectTimeDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, collectTimeDate_);
      }
      if (collectTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, collectTime_);
      }
      if (!getDevIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, devIp_);
      }
      if (!getRawMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, rawMsg_);
      }
      if (!getDevTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, devType_);
      }
      if (!getSerialNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, serialNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.learning.LogMessageOuterClass.LogMessage)) {
        return super.equals(obj);
      }
      cn.learning.LogMessageOuterClass.LogMessage other = (cn.learning.LogMessageOuterClass.LogMessage) obj;

      boolean result = true;
      result = result && getLogType()
          .equals(other.getLogType());
      result = result && getCollectTimeHour()
          .equals(other.getCollectTimeHour());
      result = result && (getNetDom()
          == other.getNetDom());
      result = result && getCollectIp()
          .equals(other.getCollectIp());
      result = result && getCollectTimeDate()
          .equals(other.getCollectTimeDate());
      result = result && (getCollectTime()
          == other.getCollectTime());
      result = result && getDevIp()
          .equals(other.getDevIp());
      result = result && getRawMsg()
          .equals(other.getRawMsg());
      result = result && getDevType()
          .equals(other.getDevType());
      result = result && getSerialNum()
          .equals(other.getSerialNum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLogType().hashCode();
      hash = (37 * hash) + COLLECT_TIME_HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getCollectTimeHour().hashCode();
      hash = (37 * hash) + NET_DOM_FIELD_NUMBER;
      hash = (53 * hash) + getNetDom();
      hash = (37 * hash) + COLLECT_IP_FIELD_NUMBER;
      hash = (53 * hash) + getCollectIp().hashCode();
      hash = (37 * hash) + COLLECT_TIME_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getCollectTimeDate().hashCode();
      hash = (37 * hash) + COLLECT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCollectTime());
      hash = (37 * hash) + DEV_IP_FIELD_NUMBER;
      hash = (53 * hash) + getDevIp().hashCode();
      hash = (37 * hash) + RAW_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getRawMsg().hashCode();
      hash = (37 * hash) + DEV_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDevType().hashCode();
      hash = (37 * hash) + SERIAL_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNum().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.learning.LogMessageOuterClass.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.learning.LogMessageOuterClass.LogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.learning.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.learning.LogMessage)
        cn.learning.LogMessageOuterClass.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.learning.LogMessageOuterClass.internal_static_cn_learning_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.learning.LogMessageOuterClass.internal_static_cn_learning_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.learning.LogMessageOuterClass.LogMessage.class, cn.learning.LogMessageOuterClass.LogMessage.Builder.class);
      }

      // Construct using cn.learning.LogMessageOuterClass.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        logType_ = "";

        collectTimeHour_ = "";

        netDom_ = 0;

        collectIp_ = "";

        collectTimeDate_ = "";

        collectTime_ = 0L;

        devIp_ = "";

        rawMsg_ = "";

        devType_ = "";

        serialNum_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.learning.LogMessageOuterClass.internal_static_cn_learning_LogMessage_descriptor;
      }

      public cn.learning.LogMessageOuterClass.LogMessage getDefaultInstanceForType() {
        return cn.learning.LogMessageOuterClass.LogMessage.getDefaultInstance();
      }

      public cn.learning.LogMessageOuterClass.LogMessage build() {
        cn.learning.LogMessageOuterClass.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.learning.LogMessageOuterClass.LogMessage buildPartial() {
        cn.learning.LogMessageOuterClass.LogMessage result = new cn.learning.LogMessageOuterClass.LogMessage(this);
        result.logType_ = logType_;
        result.collectTimeHour_ = collectTimeHour_;
        result.netDom_ = netDom_;
        result.collectIp_ = collectIp_;
        result.collectTimeDate_ = collectTimeDate_;
        result.collectTime_ = collectTime_;
        result.devIp_ = devIp_;
        result.rawMsg_ = rawMsg_;
        result.devType_ = devType_;
        result.serialNum_ = serialNum_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.learning.LogMessageOuterClass.LogMessage) {
          return mergeFrom((cn.learning.LogMessageOuterClass.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.learning.LogMessageOuterClass.LogMessage other) {
        if (other == cn.learning.LogMessageOuterClass.LogMessage.getDefaultInstance()) return this;
        if (!other.getLogType().isEmpty()) {
          logType_ = other.logType_;
          onChanged();
        }
        if (!other.getCollectTimeHour().isEmpty()) {
          collectTimeHour_ = other.collectTimeHour_;
          onChanged();
        }
        if (other.getNetDom() != 0) {
          setNetDom(other.getNetDom());
        }
        if (!other.getCollectIp().isEmpty()) {
          collectIp_ = other.collectIp_;
          onChanged();
        }
        if (!other.getCollectTimeDate().isEmpty()) {
          collectTimeDate_ = other.collectTimeDate_;
          onChanged();
        }
        if (other.getCollectTime() != 0L) {
          setCollectTime(other.getCollectTime());
        }
        if (!other.getDevIp().isEmpty()) {
          devIp_ = other.devIp_;
          onChanged();
        }
        if (!other.getRawMsg().isEmpty()) {
          rawMsg_ = other.rawMsg_;
          onChanged();
        }
        if (!other.getDevType().isEmpty()) {
          devType_ = other.devType_;
          onChanged();
        }
        if (!other.getSerialNum().isEmpty()) {
          serialNum_ = other.serialNum_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.learning.LogMessageOuterClass.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.learning.LogMessageOuterClass.LogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object logType_ = "";
      /**
       * <code>string log_type = 1;</code>
       */
      public java.lang.String getLogType() {
        java.lang.Object ref = logType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string log_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLogTypeBytes() {
        java.lang.Object ref = logType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log_type = 1;</code>
       */
      public Builder setLogType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string log_type = 1;</code>
       */
      public Builder clearLogType() {
        
        logType_ = getDefaultInstance().getLogType();
        onChanged();
        return this;
      }
      /**
       * <code>string log_type = 1;</code>
       */
      public Builder setLogTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object collectTimeHour_ = "";
      /**
       * <code>string collect_time_hour = 2;</code>
       */
      public java.lang.String getCollectTimeHour() {
        java.lang.Object ref = collectTimeHour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          collectTimeHour_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string collect_time_hour = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCollectTimeHourBytes() {
        java.lang.Object ref = collectTimeHour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectTimeHour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string collect_time_hour = 2;</code>
       */
      public Builder setCollectTimeHour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        collectTimeHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string collect_time_hour = 2;</code>
       */
      public Builder clearCollectTimeHour() {
        
        collectTimeHour_ = getDefaultInstance().getCollectTimeHour();
        onChanged();
        return this;
      }
      /**
       * <code>string collect_time_hour = 2;</code>
       */
      public Builder setCollectTimeHourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        collectTimeHour_ = value;
        onChanged();
        return this;
      }

      private int netDom_ ;
      /**
       * <code>int32 net_dom = 3;</code>
       */
      public int getNetDom() {
        return netDom_;
      }
      /**
       * <code>int32 net_dom = 3;</code>
       */
      public Builder setNetDom(int value) {
        
        netDom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 net_dom = 3;</code>
       */
      public Builder clearNetDom() {
        
        netDom_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object collectIp_ = "";
      /**
       * <code>string collect_ip = 4;</code>
       */
      public java.lang.String getCollectIp() {
        java.lang.Object ref = collectIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          collectIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string collect_ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCollectIpBytes() {
        java.lang.Object ref = collectIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string collect_ip = 4;</code>
       */
      public Builder setCollectIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        collectIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string collect_ip = 4;</code>
       */
      public Builder clearCollectIp() {
        
        collectIp_ = getDefaultInstance().getCollectIp();
        onChanged();
        return this;
      }
      /**
       * <code>string collect_ip = 4;</code>
       */
      public Builder setCollectIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        collectIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object collectTimeDate_ = "";
      /**
       * <code>string collect_time_date = 5;</code>
       */
      public java.lang.String getCollectTimeDate() {
        java.lang.Object ref = collectTimeDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          collectTimeDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string collect_time_date = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCollectTimeDateBytes() {
        java.lang.Object ref = collectTimeDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectTimeDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string collect_time_date = 5;</code>
       */
      public Builder setCollectTimeDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        collectTimeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string collect_time_date = 5;</code>
       */
      public Builder clearCollectTimeDate() {
        
        collectTimeDate_ = getDefaultInstance().getCollectTimeDate();
        onChanged();
        return this;
      }
      /**
       * <code>string collect_time_date = 5;</code>
       */
      public Builder setCollectTimeDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        collectTimeDate_ = value;
        onChanged();
        return this;
      }

      private long collectTime_ ;
      /**
       * <code>int64 collect_time = 6;</code>
       */
      public long getCollectTime() {
        return collectTime_;
      }
      /**
       * <code>int64 collect_time = 6;</code>
       */
      public Builder setCollectTime(long value) {
        
        collectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 collect_time = 6;</code>
       */
      public Builder clearCollectTime() {
        
        collectTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object devIp_ = "";
      /**
       * <code>string dev_ip = 7;</code>
       */
      public java.lang.String getDevIp() {
        java.lang.Object ref = devIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dev_ip = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDevIpBytes() {
        java.lang.Object ref = devIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dev_ip = 7;</code>
       */
      public Builder setDevIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dev_ip = 7;</code>
       */
      public Builder clearDevIp() {
        
        devIp_ = getDefaultInstance().getDevIp();
        onChanged();
        return this;
      }
      /**
       * <code>string dev_ip = 7;</code>
       */
      public Builder setDevIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rawMsg_ = "";
      /**
       * <code>string raw_msg = 8;</code>
       */
      public java.lang.String getRawMsg() {
        java.lang.Object ref = rawMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rawMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string raw_msg = 8;</code>
       */
      public com.google.protobuf.ByteString
          getRawMsgBytes() {
        java.lang.Object ref = rawMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rawMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string raw_msg = 8;</code>
       */
      public Builder setRawMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rawMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string raw_msg = 8;</code>
       */
      public Builder clearRawMsg() {
        
        rawMsg_ = getDefaultInstance().getRawMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string raw_msg = 8;</code>
       */
      public Builder setRawMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rawMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object devType_ = "";
      /**
       * <code>string dev_type = 9;</code>
       */
      public java.lang.String getDevType() {
        java.lang.Object ref = devType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dev_type = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDevTypeBytes() {
        java.lang.Object ref = devType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dev_type = 9;</code>
       */
      public Builder setDevType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dev_type = 9;</code>
       */
      public Builder clearDevType() {
        
        devType_ = getDefaultInstance().getDevType();
        onChanged();
        return this;
      }
      /**
       * <code>string dev_type = 9;</code>
       */
      public Builder setDevTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serialNum_ = "";
      /**
       * <code>string serial_num = 10;</code>
       */
      public java.lang.String getSerialNum() {
        java.lang.Object ref = serialNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serialNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serial_num = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNumBytes() {
        java.lang.Object ref = serialNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serial_num = 10;</code>
       */
      public Builder setSerialNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serialNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serial_num = 10;</code>
       */
      public Builder clearSerialNum() {
        
        serialNum_ = getDefaultInstance().getSerialNum();
        onChanged();
        return this;
      }
      /**
       * <code>string serial_num = 10;</code>
       */
      public Builder setSerialNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serialNum_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.learning.LogMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.learning.LogMessage)
    private static final cn.learning.LogMessageOuterClass.LogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.learning.LogMessageOuterClass.LogMessage();
    }

    public static cn.learning.LogMessageOuterClass.LogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    public cn.learning.LogMessageOuterClass.LogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_learning_LogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_learning_LogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/resources/log_message.proto\022\013" +
      "cn.learning\"\326\001\n\nLogMessage\022\020\n\010log_type\030\001" +
      " \001(\t\022\031\n\021collect_time_hour\030\002 \001(\t\022\017\n\007net_d" +
      "om\030\003 \001(\005\022\022\n\ncollect_ip\030\004 \001(\t\022\031\n\021collect_" +
      "time_date\030\005 \001(\t\022\024\n\014collect_time\030\006 \001(\003\022\016\n" +
      "\006dev_ip\030\007 \001(\t\022\017\n\007raw_msg\030\010 \001(\t\022\020\n\010dev_ty" +
      "pe\030\t \001(\t\022\022\n\nserial_num\030\n \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_learning_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_learning_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_learning_LogMessage_descriptor,
        new java.lang.String[] { "LogType", "CollectTimeHour", "NetDom", "CollectIp", "CollectTimeDate", "CollectTime", "DevIp", "RawMsg", "DevType", "SerialNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
